name: TagBot
on:
  push:
    branches:
      - main
    paths:
      - 'Project.toml'
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.SSH_KEY }}
